//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen1ra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public string nombre { get; set; }
        public int codigobarra { get; set; }
        public string familia { get; set; }
        public Nullable<int> precio { get; set; }
        public Nullable<int> descuentomax { get; set; }
        public string descripcion { get; set; }
    }
}
